#\uEB00
60160=sugarcoated-blue-sugar-floor|sugarcoated-blue-sugar-floor-ui
#\uEAFF
60159=sugarcoated-pink-sugar-floor|sugarcoated-pink-sugar-floor-ui
#\uEAFE
60158=sugarcoated-cocoa-floor|sugarcoated-cocoa-floor-ui
#\uEAFD
60157=sugarcoated-crystal-floor|sugarcoated-crystal-floor-ui
#\uEAFC
60156=sugarcoated-crystalline-jelly|sugarcoated-crystalline-jelly-ui
#\uEAFB
60155=sugarcoated-crystal-wall|sugarcoated-crystal-wall-ui
#\uEAFA
60154=sugarcoated-core-bonbon|sugarcoated-core-bonbon-ui
#\uEAF9
60153=sugarcoated-sugar|sugarcoated-sugar-ui
#\uEAF8
60152=sugarcoated-cocoa|sugarcoated-cocoa-ui
#\uEAF7
60151=sugarcoated-jelly|sugarcoated-jelly-ui
#\uEAF6
60150=sugarcoated-baby-pepper|sugarcoated-baby-pepper-ui
#\uEAF5
60149=sugarcoated-baby-mint|sugarcoated-baby-mint-ui
#\uEAF4
60148=sugarcoated-sweet-mother|sugarcoated-sweet-mother-ui
#\uEAF3
60147=sugarcoated-sweet-mother-missile|sugarcoated-sweet-mother-missile-ui
#\uEAF2
60146=sugarcoated-speedy|sugarcoated-speedy-ui
